Test project in a subdir

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1,6 +1,10 @@
 format_version: "20"
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 
+app:
+  envs:
+  - ORIG_BITRISE_SOURCE_DIR: $BITRISE_SOURCE_DIR
+
 workflows:
   ci:
     before_run:
@@ -15,38 +19,73 @@ workflows:
     - git::https://github.com/bitrise-steplib/steps-check.git: { }
 
   test:
-    description: Test with all inputs defined
-    envs:
-    - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-android-sdk22.git
-    - GRADLE_BUILD_FILE_PATH: ./build.gradle
-    - GRADLEW_PATH: ./gradlew
-    - BRANCH: master
-    after_run:
-    - _common
-
-  test-no-root-buildfile:
-    description: Test without GRADLE_BUILD_FILE_PATH
-    envs:
-    - SAMPLE_APP_URL: https://github.com/bitrise-samples/android-empty-library.git
-    - GRADLE_BUILD_FILE_PATH: ""
-    - GRADLEW_PATH: ./gradlew
-    - BRANCH: master
-    after_run:
-    - _common
+    description:  Test Gradle Groovy DSL support.
+    steps:
+    - bundle::run_step_test:
+        inputs:
+        - test_app_repo_url: https://github.com/bitrise-samples/sample-apps-android-sdk22.git
+        - test_app_branch: master
+        - gradle_build_script_path: ./build.gradle
 
   test-gradle-kts:
-    description: Test Gradle Kotlin DSL support
-    envs:
-    - SAMPLE_APP_URL: https://github.com/bitrise-samples/android-gradle-kotlin-dsl.git
-    - GRADLE_BUILD_FILE_PATH: ./build.gradle.kts
-    - GRADLEW_PATH: ./gradlew
-    - BRANCH: master
-    after_run:
-    - _common
+    description: Test Gradle Kotlin DSL support.
+    steps:
+    - bundle::run_step_test:
+        inputs:
+        - test_app_repo_url: https://github.com/bitrise-samples/android-gradle-kotlin-dsl.git
+        - test_app_branch: master
+        - gradle_build_script_path: ./build.gradle.kts
 
-  # ----------------------------------------------------------------
-  # --- workflow to Step Test
-  _common:
+  test-no-root-buildfile:
+    description: Test without explicit Gradle build script path.
+    steps:
+    - bundle::run_step_test:
+        inputs:
+        - test_app_repo_url: https://github.com/bitrise-samples/android-empty-library.git
+        - test_app_branch: master
+        - gradle_build_script_path: ./build.gradle.kts
+
+  test-project-in-sub-dir:
+    description: Test Gradle project placed in a sub directory.
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -ex
+            rm -rf ./_tmp
+    - change-workdir:
+        title: Switch working dir to test ./_tmp/subdir dir
+        run_if: true
+        inputs:
+        - path: ./_tmp/subdir
+        - is_create_path: true
+    - bundle::clone_repo:
+        inputs:
+        - test_app_repo_url: https://github.com/bitrise-samples/android-gradle-kotlin-dsl.git
+        - test_app_branch: master
+    - change-workdir:
+        title: Switch working dir to test ./_tmp dir
+        run_if: true
+        inputs:
+        - path: $ORIG_BITRISE_SOURCE_DIR/_tmp
+        - is_create_path: true
+    - path::./:
+        inputs:
+        - project_root_dir: ./subdir
+    - script:
+        title: Output test
+        is_always_run: true
+        inputs:
+        - content: |-
+            echo "BITRISE_GRADLE_TEST_RESULT: $BITRISE_GRADLE_TEST_RESULT"
+
+step_bundles:
+  run_step_test:
+    inputs:
+    - test_app_repo_url:
+    - test_app_branch:
+    - gradle_build_script_path:
     steps:
     - script:
         inputs:
@@ -60,25 +99,37 @@ workflows:
         inputs:
         - path: ./_tmp
         - is_create_path: true
-    - script:
+    - bundle::clone_repo:
         inputs:
-        - content: |-
-            #!/usr/bin/env bash
-            if [[ -z "${SAMPLE_APP_URL}" ]]; then
-              echo "error: there is no SAMPLE_APP_URL env var specified"
-              exit 1
-            elif [[ -z "${COMMIT}" && -z "${BRANCH}" ]]; then
-              echo "error: can't checkout: there is no BRANCH or COMMIT env var specified"
-              exit 1
-            fi
-            git init
-            git remote add origin "${SAMPLE_APP_URL}"
-            git fetch || exit 1
-            [[ -n "${COMMIT}" ]] && git checkout "${COMMIT}" || git checkout "${BRANCH}"
+        - test_app_repo_url: $test_app_repo_url
+        - test_app_branch: $test_app_branch
     - path::./:
+        inputs:
+        - gradle_build_script_path: $gradle_build_script_path
     - script:
         title: Output test
         is_always_run: true
         inputs:
         - content: |-
             echo "BITRISE_GRADLE_TEST_RESULT: $BITRISE_GRADLE_TEST_RESULT"
+
+  clone_repo:
+    inputs:
+    - test_app_repo_url:
+    - test_app_branch:
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            if [[ -z "${test_app_repo_url}" ]]; then
+              echo "error: there is no test_app_repo_url specified"
+              exit 1
+            elif [[ -z "${test_app_branch}" ]]; then
+              echo "error: can't checkout: there is no test_app_branch specified"
+              exit 1
+            fi
+            git init
+            git remote add origin "${test_app_repo_url}"
+            git fetch || exit 1
+            git checkout "${test_app_branch}"
